### ISSUE TITLE
Illegal data causes NoMethodError

### ISSUE THREAD

**Issue by nokute78** [tagomoris/msgpack-inspect#6]
Partial msgpack data causes `NoMethodError`.

`IO#read` ( and `dig` ) in each `generate_*` need next data.
Then if no/partial data comes, `IO#read` returns `nil` and it causes `NoMethodError`.
## How to reproduce

e.g. Only `HEADER_FIXMAP` and no mapped data.
`$ printf "\x82" | msgpack-inspect -`
## Result

```
$ printf "\x82" | msgpack-inspect -
/home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/inspector.rb:76:in `dig': undefined method `b' for nil:NilClass (NoMethodError)
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/inspector.rb:195:in `block in generate_map'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/inspector.rb:193:in `times'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/inspector.rb:193:in `generate_map'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/inspector.rb:367:in `generate'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/inspector.rb:78:in `dig'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/inspector.rb:20:in `initialize'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect.rb:10:in `new'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect.rb:10:in `inspect'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/command.rb:39:in `execute'
    from ./exe/msgpack-inspect:6:in `<main>'
```

**Comment by tagomoris** [comment]
Version 0.1.3 with streaming format shows another output:

```
$ printf "\x82" | bundle exec exe/msgpack-inspect -
---
- format: "fixmap"
  header: "0x82"
  length: 2
  children:
    - key:
```

Ideally, we should print errors to show insufficient input data for map with `length: 2`, with empty `children`.

**Comment by nokute78** [comment]
Thank you for updating! 
I tested v0.1.3, and first issue was fixed.

However, in another case, msgpack-inspect still raises NoMethodError.
Only header data seems to cause this.
(ex. The input data is only FIXSTR_HEADER (0xa5).)

```
$ printf "\xa5" | msgpack-inspect -
---
- format: "fixstr"
  header: "0xa5"
/home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/node.rb:56:in `hex': undefined method `unpack' for nil:NilClass (NoMethodError)
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/node.rb:228:in `attributes_string'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/node.rb:87:in `attributes'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/streamer.rb:73:in `attributes'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/inspector.rb:50:in `dig'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/inspector.rb:25:in `block (2 levels) in inspect'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/streamer.rb:36:in `object'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/inspector.rb:24:in `block in inspect'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/streamer.rb:32:in `objects'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/inspector.rb:17:in `inspect'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect.rb:11:in `inspect'
    from /home/taka/git/oss/pull_req/msgpack-inspect/lib/msgpack/inspect/command.rb:45:in `execute'
    from exe/msgpack-inspect:7:in `<main>'

```
